# Do not edit this file, it’s used by GitHub Actions.
DB_DSN="pgsql:host=postgres;port=5432;dbname=test"
DB_USER="postgres"
DB_PASSWORD="postgres"
DB_SCHEMA="public"
DB_TABLE_PREFIX=""

SECURITY_KEY="abcde12345"

# Set this to the `entryUrl` param in the `codeception.yml` file.
DEFAULT_SITE_URL="https://test.craftcms.test/index.php"
FROM_EMAIL_NAME="Craft CMS"
FROM_EMAIL_ADDRESS="info@craftcms.com"
